Added Chapter 3.4 - Posting comments and removing friends
Steam-Bot-Basics/node-steam-guide pull request #1
Opened 2018-10-23 13:15 UTC by DentFuse

2018-10-23 15:29 UTC, andrewda requested changes

2018-10-23 15:29 UTC, andrewda commented on Chapter 3 - User Interaction/Chapter 3.4 - Commenting on Profile & Removing Friends/project4.js
> +});
Newline at EOF

2018-10-24 10:44 UTC, DentFuse commented on Chapter 3 - User Interaction/Chapter 3.4 - Commenting on Profile & Removing Friends/project4.js
> +});
Added newline at EOF in 364f48e

2018-10-24 15:34 UTC, DentFuse commented
@andrewda Hi, can you please merge this PR, I'd do it myself but I'm actually taking part in the hacktoberfest and so I don't want to have my own pull requests approved by me.

2018-11-11 05:04 UTC, merged

2018-11-11 05:04 UTC, xmwx38 commented
All done.  It has been merged!  @DentFuse